### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character u'\u2014' in position 11: illegal multibyte sequence

### ISSUE THREAD

**Issue by morioking** [morioking/SearchDisc#8]
`miles davis so what`

で発生。

**Comment by morioking** [comment]
下記でも発生

`kassem mosse workshop 19`

`UnicodeEncodeError: 'cp932' codec can't encode character u'\u200e' in position 42: illegal multibyte sequence`

**Comment by morioking** [comment]
修正完了

**Comment by morioking** [comment]
再発

```
C:\Users\morishiy\Documents\GitHub\SearchDisc>python sd.py
input keyword...
TODD TERJE / SON OF SAM - DIGITAL DUBPLATES
2016/06/17-17:14 start search...
mp3va
Beatport
   https://www.beatport.com/artist/todd-terje/14667/releases
     >  Todd Terje :: Beatport
   https://www.beatport.com/track/dra-te-h-lvete-todd-terje-acid-remix/7738205
     >  Traceback (most recent call last):
  File "sd.py", line 119, in <module>
    shop_class_list.append(Shop(a['shopname'], a['shopurl'],keyword))
  File "sd.py", line 34, in __init__
    self.createDiskList()
  File "sd.py", line 64, in createDiskList
    print '     > ',title
UnicodeEncodeError: 'cp932' codec can't encode character u'\xe6' in position 8: illegal multibyte seq
```

**Comment by morioking** [comment]
解決の手がかり
http://d.hatena.ne.jp/nishiohirokazu/20120112/1326355987
